name: gaitutils
channels:
  - conda-forge
dependencies:
  - btk
  - configobj
  - flask
  - freetype
  - future
  - matplotlib
  - numpy
  - scipy
  - python
  - openpyxl
  - pip
  - plotly
  - pyqt
  - spyder
  - jupyter
  - urllib3
  - werkzeug
  - xlrd
  - xlsxwriter
  - xlutils
  - pip:
    - dash
    - kaleido
    - dash-daq
    - flake8
    - pytest
    - pathlib
    - https://github.com/jjnurminen/gaitutils/archive/master.zip
    - https://github.com/jjnurminen/ulstools/archive/master.zip
    - https://github.com/jjnurminen/configdot/archive/master.zip

